export default [
  {
    name: "Plain Pasta",
    servings: 1,
    comps: [
      {
        name: "Pasta",
        sourceName: "Pasta, dry, enriched",
        state: "dry",
        quantity: 220,
        unit: "G",
        nutrients: [
          {
            name: "Magnesium",
            unit: "MG",
            value: 116.6,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 13.2,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 46.2,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 490.6,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 3.102,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 7.26,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 164.34,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.242,
          },
          {
            name: "Fat",
            unit: "G",
            value: 3.322,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 7.04,
          },
          {
            name: "Protein",
            unit: "G",
            value: 28.6,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Butter",
        sourceName: "Butter, salted",
        state: "salted",
        quantity: 20,
        unit: "G",
        nutrients: [
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.004,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 0.4,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0.034,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 4.8,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.018,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 128.6,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.464,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 136.8,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fat",
            unit: "G",
            value: 16.22,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 0.012,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.17,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 4.8,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Magnesium",
        unit: "MG",
        value: 117,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 141.79999999999998,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 51,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 495.40000000000003,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 3.1199999999999997,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 136.8,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 7.263999999999999,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 164.352,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 0,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0.034,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.706,
      },
      {
        name: "Fat",
        unit: "G",
        value: 19.541999999999998,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 7.04,
      },
      {
        name: "Protein",
        unit: "G",
        value: 28.770000000000003,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "White Bread and Tea",
    servings: 1,
    comps: [
      {
        name: "Bread",
        sourceName: "Bread, white wheat",
        state: "white",
        quantity: 100,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 2.15,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 43.9,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 684,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 127,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.95,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.38,
          },
          {
            name: "Protein",
            unit: "G",
            value: 10.7,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 9.2,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 4.89,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 26,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 478,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Tea",
        sourceName: "Beverages, tea, black, ready to drink",
        state: "black",
        quantity: 250,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 0,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 0,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 0,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 0,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 5,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Sugar",
        sourceName: "Sugar-apples, (sweetsop), raw",
        state: "raw",
        quantity: 20,
        unit: "G",
        nutrients: [
          {
            name: "Zinc",
            unit: "MG",
            value: 0.02,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.058,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 4.72,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 4.8,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 49.4,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0.88,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.12,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 4.2,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 1.8,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 7.26,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.412,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Fat",
        unit: "G",
        value: 2.2079999999999997,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 48.62,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 688.8,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 176.4,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 0.97,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.38,
      },
      {
        name: "Protein",
        unit: "G",
        value: 11.112,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 10.08,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 5.01,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 30.2,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 484.8,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 7.26,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "Instant Noodles and Cola",
    servings: 1,
    comps: [
      {
        name: "Soup, Ramen Noodle",
        sourceName: "Soup, ramen noodle, any flavor, dry",
        state: "dry",
        quantity: 180,
        unit: "G",
        nutrients: [
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0.45,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 1.8,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0.54,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 37.8,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 325.8,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 1.08,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 4.392,
          },
          {
            name: "Fat",
            unit: "G",
            value: 31.68,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 108.54,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 5.22,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 7.398,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 45,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 3348,
          },
          {
            name: "Protein",
            unit: "G",
            value: 18.36,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Cola",
        sourceName: "Beverages, carbonated, cola, fast-food cola",
        state: "carbonated",
        quantity: 350,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 0.07,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 7,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 7,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.245,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.385,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 0,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 14,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.07,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 33.46,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0.45,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 1.8,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 0.54,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 44.8,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 332.8,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 1.1500000000000001,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 4.392,
      },
      {
        name: "Fat",
        unit: "G",
        value: 31.75,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 142,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 5.22,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 7.7829999999999995,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 45,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 3362,
      },
      {
        name: "Protein",
        unit: "G",
        value: 18.605,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "Sugary Cereal",
    servings: 1,
    comps: [
      {
        name: "cereals",
        sourceName: "Cereals ready-to-eat, ALPEN",
        state: "ready-to-eat",
        quantity: 60,
        unit: "G",
        nutrients: [
          { name: "Vitamin E", unit: "MG", value: 0.306 },
          { name: "Vitamin A", unit: "UG", value: 0 },
          { name: "Calcium", unit: "MG", value: 88.2 },
          { name: "Zinc", unit: "MG", value: 1.8 },
          { name: "Fat", unit: "G", value: 1.98 },
          { name: "Carbohydrate", unit: "G", value: 45.42 },
          { name: "Vitamin C", unit: "MG", value: 5.22 },
          { name: "Vitamin B12", unit: "UG", value: 0.072 },
          { name: "Fiber", unit: "G", value: 5.46 },
          { name: "Iron", unit: "MG", value: 1.8 },
          { name: "Magnesium", unit: "MG", value: 56.4 },
          { name: "Protein", unit: "G", value: 6.72 },
          { name: "Potassium", unit: "MG", value: 250.8 },
          { name: "Sodium", unit: "MG", value: 16.2 },
          { name: "Vitamin D", unit: "UG", value: 0 },
        ],
      },
      {
        name: "Sugar",
        sourceName: "Sugar-apples, (sweetsop), raw",
        state: "raw",
        quantity: 25,
        unit: "G",
        nutrients: [
          { name: "Zinc", unit: "MG", value: 0.025 },
          { name: "Vitamin A", unit: "UG", value: 0 },
          { name: "Fat", unit: "G", value: 0.0725 },
          { name: "Carbohydrate", unit: "G", value: 5.9 },
          { name: "Calcium", unit: "MG", value: 6 },
          { name: "Potassium", unit: "MG", value: 61.75 },
          { name: "Fiber", unit: "G", value: 1.1 },
          { name: "Iron", unit: "MG", value: 0.15 },
          { name: "Magnesium", unit: "MG", value: 5.25 },
          { name: "Sodium", unit: "MG", value: 2.25 },
          { name: "Vitamin C", unit: "MG", value: 9.075 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
          { name: "Protein", unit: "G", value: 0.515 },
        ],
      },
      {
        name: "Milk",
        sourceName: "Milk, buttermilk, fluid, whole",
        state: "whole",
        quantity: 120,
        unit: "G",
        nutrients: [
          { name: "Vitamin D", unit: "UG", value: 1.56 },
          { name: "Protein", unit: "G", value: 3.852 },
          { name: "Fiber", unit: "G", value: 0 },
          { name: "Iron", unit: "MG", value: 0.036 },
          { name: "Magnesium", unit: "MG", value: 12 },
          { name: "Vitamin A", unit: "UG", value: 56.4 },
          { name: "Vitamin C", unit: "MG", value: 0 },
          { name: "Vitamin B12", unit: "UG", value: 0.552 },
          { name: "Fat", unit: "G", value: 3.972 },
          { name: "Carbohydrate", unit: "G", value: 5.856 },
          { name: "Calcium", unit: "MG", value: 138 },
          { name: "Potassium", unit: "MG", value: 162 },
          { name: "Zinc", unit: "MG", value: 0.456 },
          { name: "Vitamin E", unit: "MG", value: 0.084 },
          { name: "Sodium", unit: "MG", value: 126 },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      { name: "Vitamin E", unit: "MG", value: 0.39 },
      { name: "Vitamin A", unit: "UG", value: 56.4 },
      { name: "Calcium", unit: "MG", value: 232.2 },
      { name: "Zinc", unit: "MG", value: 2.281 },
      { name: "Fat", unit: "G", value: 6.0245 },
      { name: "Carbohydrate", unit: "G", value: 57.176 },
      { name: "Vitamin C", unit: "MG", value: 14.294999999999998 },
      { name: "Vitamin B12", unit: "UG", value: 0.624 },
      { name: "Fiber", unit: "G", value: 6.5600000000000005 },
      { name: "Iron", unit: "MG", value: 1.986 },
      { name: "Magnesium", unit: "MG", value: 73.65 },
      { name: "Protein", unit: "G", value: 11.087 },
      { name: "Potassium", unit: "MG", value: 474.55 },
      { name: "Sodium", unit: "MG", value: 144.45 },
      { name: "Vitamin D", unit: "UG", value: 1.56 },
    ],
  },
  {
    name: "Banana Oatmeal",
    servings: 1,
    comps: [
      {
        name: "Oats",
        sourceName: "Oat bran, raw",
        state: "raw",
        quantity: 50,
        unit: "G",
        nutrients: [
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 29,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 283,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 1.555,
          },
          {
            name: "Fat",
            unit: "G",
            value: 3.515,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 33.1,
          },
          {
            name: "Protein",
            unit: "G",
            value: 8.65,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 7.7,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 2.705,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 117.5,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 2,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.505,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Banana",
        sourceName: "Bananas, raw",
        state: "raw",
        quantity: 120,
        unit: "G",
        nutrients: [
          {
            name: "Vitamin A",
            unit: "UG",
            value: 3.6,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 27.36,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 10.44,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 3.12,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.312,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 32.4,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 1.2,
          },
          {
            name: "Protein",
            unit: "G",
            value: 1.308,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 6,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 429.6,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.18,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.396,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.12,
          },
        ],
      },
      {
        name: "Milk",
        sourceName: "Milk, buttermilk, fluid, whole",
        state: "whole",
        quantity: 250,
        unit: "G",
        nutrients: [
          {
            name: "Vitamin D",
            unit: "UG",
            value: 3.25,
          },
          {
            name: "Protein",
            unit: "G",
            value: 8.025,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.075,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 25,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 117.5,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 1.15,
          },
          {
            name: "Fat",
            unit: "G",
            value: 8.275,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 12.2,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 287.5,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 337.5,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.95,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.175,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 262.5,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Vitamin A",
        unit: "UG",
        value: 121.1,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 322.5,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 1050.1,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 2.6849999999999996,
      },
      {
        name: "Fat",
        unit: "G",
        value: 12.186,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 72.66,
      },
      {
        name: "Protein",
        unit: "G",
        value: 17.983,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 10.82,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 3.092,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 174.9,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 265.7,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 10.44,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 1.15,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.8,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 3.25,
      },
    ],
  },
  {
    name: "Rice and Beans",
    servings: 2,
    comps: [
      {
        name: "Rice, white",
        sourceName: "Rice, white, medium-grain, raw, enriched",
        state: "raw",
        quantity: 200,
        unit: "G",
        nutrients: [
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Protein",
            unit: "G",
            value: 13.22,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 2.8,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 8.72,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 70,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 2,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Fat",
            unit: "G",
            value: 1.16,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 158.6,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 18,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 172,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 2.32,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.22,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Beans",
        sourceName: "Beans, navy, mature seeds, cooked, boiled, with salt",
        state: "boiled",
        quantity: 180,
        unit: "G",
        nutrients: [
          {
            name: "Protein",
            unit: "G",
            value: 14.814,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 4.248,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 95.4,
          },
          {
            name: "Fat",
            unit: "G",
            value: 1.116,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 124.2,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 700.2,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 1.854,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.018,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 1.62,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 18.9,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 46.8,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 426.6,
          },
        ],
      },
      {
        name: "Tomato",
        sourceName: "Tomatoes, green, raw",
        state: "raw",
        quantity: 80,
        unit: "G",
        nutrients: [
          {
            name: "Fiber",
            unit: "G",
            value: 0.88,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.304,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 4.08,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 25.6,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 18.72,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.96,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.408,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 8,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 10.4,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 10.4,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 163.2,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.056,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.16,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Onion",
        sourceName: "Onions, raw",
        state: "raw",
        quantity: 50,
        unit: "G",
        nutrients: [
          {
            name: "Calcium",
            unit: "MG",
            value: 11.5,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 73,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.085,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.01,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.05,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 4.67,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 3.7,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.55,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0.85,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.105,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 5,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 2,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Vitamin A",
        unit: "UG",
        value: 12.8,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0,
      },
      {
        name: "Protein",
        unit: "G",
        value: 14.772,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 11.715,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 6.7405,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 89.2,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 220.5,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 12.02,
      },
      {
        name: "Fat",
        unit: "G",
        value: 1.2429999999999999,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 107.07499999999999,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 82.05,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 554.2,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 2.1574999999999998,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.276,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "Egg and Toast",
    servings: 1,
    comps: [
      {
        name: "Egg",
        sourceName: "Egg, whole, cooked, hard-boiled",
        state: "boiled",
        quantity: 100,
        unit: "G",
        nutrients: [
          { name: "Vitamin E", unit: "MG", value: 1.03 },
          { name: "Fiber", unit: "G", value: 0 },
          { name: "Vitamin A", unit: "UG", value: 149 },
          { name: "Vitamin D", unit: "UG", value: 2.2 },
          { name: "Protein", unit: "G", value: 12.6 },
          { name: "Iron", unit: "MG", value: 1.19 },
          { name: "Magnesium", unit: "MG", value: 10 },
          { name: "Sodium", unit: "MG", value: 124 },
          { name: "Vitamin C", unit: "MG", value: 0 },
          { name: "Vitamin B12", unit: "UG", value: 1.11 },
          { name: "Calcium", unit: "MG", value: 50 },
          { name: "Potassium", unit: "MG", value: 126 },
          { name: "Zinc", unit: "MG", value: 1.05 },
          { name: "Fat", unit: "G", value: 10.6 },
          { name: "Carbohydrate", unit: "G", value: 1.12 },
        ],
      },
      {
        name: "Bread, whole-wheat",
        sourceName: "Bread, whole-wheat, commercially prepared, toasted",
        state: "toasted",
        quantity: 70,
        unit: "G",
        nutrients: [
          { name: "Sodium", unit: "MG", value: 395.5 },
          { name: "Vitamin C", unit: "MG", value: 0 },
          { name: "Fiber", unit: "G", value: 5.25 },
          { name: "Iron", unit: "MG", value: 2.072 },
          { name: "Magnesium", unit: "MG", value: 69.3 },
          { name: "Protein", unit: "G", value: 11.41 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
          { name: "Vitamin A", unit: "UG", value: 0 },
          { name: "Fat", unit: "G", value: 2.849 },
          { name: "Carbohydrate", unit: "G", value: 35.84 },
          { name: "Calcium", unit: "MG", value: 91 },
          { name: "Potassium", unit: "MG", value: 228.2 },
          { name: "Zinc", unit: "MG", value: 1.505 },
          { name: "Vitamin E", unit: "MG", value: 0.441 },
          { name: "Vitamin D", unit: "UG", value: 0 },
        ],
      },
      {
        name: "Orange",
        sourceName: "Oranges, raw, Florida",
        state: "raw",
        quantity: 130,
        unit: "G",
        nutrients: [
          { name: "Vitamin E", unit: "MG", value: 0.234 },
          { name: "Protein", unit: "G", value: 0.91 },
          { name: "Fiber", unit: "G", value: 3.12 },
          { name: "Iron", unit: "MG", value: 0.117 },
          { name: "Magnesium", unit: "MG", value: 13 },
          { name: "Sodium", unit: "MG", value: 0 },
          { name: "Vitamin C", unit: "MG", value: 58.5 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
          { name: "Fat", unit: "G", value: 0.273 },
          { name: "Carbohydrate", unit: "G", value: 14.95 },
          { name: "Calcium", unit: "MG", value: 55.9 },
          { name: "Potassium", unit: "MG", value: 219.7 },
          { name: "Zinc", unit: "MG", value: 0.104 },
          { name: "Vitamin D", unit: "UG", value: 0 },
          { name: "Vitamin A", unit: "UG", value: 14.3 },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      { name: "Vitamin E", unit: "MG", value: 1.705 },
      { name: "Fiber", unit: "G", value: 8.370000000000001 },
      { name: "Vitamin A", unit: "UG", value: 163.3 },
      { name: "Vitamin D", unit: "UG", value: 2.2 },
      { name: "Protein", unit: "G", value: 24.919999999999998 },
      { name: "Iron", unit: "MG", value: 3.379 },
      { name: "Magnesium", unit: "MG", value: 92.3 },
      { name: "Sodium", unit: "MG", value: 519.5 },
      { name: "Vitamin C", unit: "MG", value: 58.5 },
      { name: "Vitamin B12", unit: "UG", value: 1.11 },
      { name: "Calcium", unit: "MG", value: 196.9 },
      { name: "Potassium", unit: "MG", value: 573.9 },
      { name: "Zinc", unit: "MG", value: 2.659 },
      { name: "Fat", unit: "G", value: 13.722 },
      { name: "Carbohydrate", unit: "G", value: 51.91 },
    ],
  },
  {
    name: "Chicken Vegetable Soup",
    servings: 2,
    comps: [
      {
        name: "Chicken, breast",
        sourceName: "Chicken, breast, boneless, skinless, raw",
        state: "raw",
        quantity: 180,
        unit: "G",
        nutrients: [
          {
            name: "Iron",
            unit: "MG",
            value: 0.6372,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 47.16,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 594,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 118.44,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 1.1772,
          },
          {
            name: "Fat",
            unit: "G",
            value: 3.474,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 7.092,
          },
          {
            name: "Protein",
            unit: "G",
            value: 40.5,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 0,
          },
        ],
      },
      {
        name: "Carrot",
        sourceName: "Carrots, raw",
        state: "raw",
        quantity: 80,
        unit: "G",
        nutrients: [
          {
            name: "Iron",
            unit: "MG",
            value: 0.24,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 9.6,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 55.2,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 4.72,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.744,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.528,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.192,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 26.4,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 256,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.192,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 7.664,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 668,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 2.24,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Spinach",
        sourceName: "Spinach, raw",
        state: "raw",
        quantity: 60,
        unit: "G",
        nutrients: [
          {
            name: "Calcium",
            unit: "MG",
            value: 59.4,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 334.8,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.318,
          },
          {
            name: "Protein",
            unit: "G",
            value: 1.716,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 1.626,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 47.4,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 47.4,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 16.86,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 1.32,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 1.218,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.234,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 2.178,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 281.4,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Potato",
        sourceName: "Potatoes, boiled, cooked in skin, flesh, with salt",
        state: "boiled",
        quantity: 150,
        unit: "G",
        nutrients: [
          {
            name: "Carbohydrate",
            unit: "G",
            value: 30.15,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.075,
          },
          {
            name: "Protein",
            unit: "G",
            value: 2.805,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 3,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.465,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 33,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 360,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 19.5,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fat",
            unit: "G",
            value: 0.15,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 7.5,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 568.5,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.45,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Iron",
        unit: "MG",
        value: 1.4840999999999998,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 68.58,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 876.65,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 290.52,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 1.0686,
      },
      {
        name: "Fat",
        unit: "G",
        value: 2.0250000000000004,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 50.196,
      },
      {
        name: "Protein",
        unit: "G",
        value: 22.8825,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 19.996,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 20.54,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.9105,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 474.7,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 3.2800000000000002,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "Fried Rice and Cola",
    servings: 2,
    comps: [
      {
        name: "Rice",
        sourceName: "Restaurant, Chinese, fried rice, without meat",
        state: "fried",
        quantity: 250,
        unit: "G",
        nutrients: [
          { name: "Magnesium", unit: "MG", value: 25 },
          { name: "Vitamin E", unit: "MG", value: 0.325 },
          { name: "Calcium", unit: "MG", value: 30 },
          { name: "Potassium", unit: "MG", value: 190 },
          { name: "Zinc", unit: "MG", value: 1.8 },
          { name: "Fat", unit: "G", value: 7.4 },
          { name: "Carbohydrate", unit: "G", value: 82 },
          { name: "Vitamin A", unit: "UG", value: 55 },
          { name: "Vitamin D", unit: "UG", value: 0 },
          { name: "Sodium", unit: "MG", value: 967.5 },
          { name: "Vitamin C", unit: "MG", value: 9.5 },
          { name: "Protein", unit: "G", value: 10.125 },
          { name: "Iron", unit: "MG", value: 1.65 },
          { name: "Fiber", unit: "G", value: 2.75 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
        ],
      },
      {
        name: "Oil",
        sourceName: "Oil, vegetable, soybean, refined",
        state: "Vegetable",
        quantity: 30,
        unit: "G",
        nutrients: [
          { name: "Vitamin E", unit: "MG", value: 2.454 },
          { name: "Protein", unit: "G", value: 0 },
          { name: "Fiber", unit: "G", value: 0 },
          { name: "Iron", unit: "MG", value: 0.006 },
          { name: "Magnesium", unit: "MG", value: 0 },
          { name: "Sodium", unit: "MG", value: 0 },
          { name: "Vitamin A", unit: "UG", value: 0 },
          { name: "Vitamin C", unit: "MG", value: 0 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
          { name: "Fat", unit: "G", value: 30 },
          { name: "Carbohydrate", unit: "G", value: 0 },
          { name: "Calcium", unit: "MG", value: 0 },
          { name: "Potassium", unit: "MG", value: 0 },
          { name: "Zinc", unit: "MG", value: 0 },
        ],
      },
      {
        name: "Cola",
        sourceName: "Beverages, carbonated, cola, fast-food cola",
        state: "carbonated",
        quantity: 330,
        unit: "ML",
        nutrients: [
          { name: "Fat", unit: "G", value: 0.066 },
          { name: "Calcium", unit: "MG", value: 6.6 },
          { name: "Potassium", unit: "MG", value: 6.6 },
          { name: "Protein", unit: "G", value: 0.231 },
          { name: "Iron", unit: "MG", value: 0.363 },
          { name: "Magnesium", unit: "MG", value: 0 },
          { name: "Sodium", unit: "MG", value: 13.2 },
          { name: "Zinc", unit: "MG", value: 0.066 },
          { name: "Vitamin D", unit: "UG", value: 0 },
          { name: "Vitamin C", unit: "MG", value: 0 },
          { name: "Vitamin B12", unit: "UG", value: 0 },
          { name: "Fiber", unit: "G", value: 0 },
          { name: "Vitamin E", unit: "MG", value: 0 },
          { name: "Vitamin A", unit: "UG", value: 0 },
          { name: "Carbohydrate", unit: "G", value: 31.548 },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      { name: "Magnesium", unit: "MG", value: 12.5 },
      { name: "Vitamin E", unit: "MG", value: 1.3895000000000002 },
      { name: "Calcium", unit: "MG", value: 18.3 },
      { name: "Potassium", unit: "MG", value: 98.3 },
      { name: "Zinc", unit: "MG", value: 0.933 },
      { name: "Fat", unit: "G", value: 18.733 },
      { name: "Carbohydrate", unit: "G", value: 56.774 },
      { name: "Vitamin A", unit: "UG", value: 27.5 },
      { name: "Vitamin D", unit: "UG", value: 0 },
      { name: "Sodium", unit: "MG", value: 490.35 },
      { name: "Vitamin C", unit: "MG", value: 4.75 },
      { name: "Protein", unit: "G", value: 5.178 },
      { name: "Iron", unit: "MG", value: 1.0095 },
      { name: "Fiber", unit: "G", value: 1.375 },
      { name: "Vitamin B12", unit: "UG", value: 0 },
    ],
  },
  {
    name: "Burger and Fries",
    servings: 1,
    comps: [
      {
        name: "Bread",
        sourceName: "Bread, white wheat",
        state: "white",
        quantity: 80,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 1.72,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 35.12,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 547.2,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 101.6,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.76,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.304,
          },
          {
            name: "Protein",
            unit: "G",
            value: 8.56,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 7.36,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 3.912,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 20.8,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 382.4,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Ground Beef",
        sourceName: "Beef, grass-fed, ground, raw",
        state: "raw",
        quantity: 150,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 19.05,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 0,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 18,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 433.5,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 6.825,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 2.955,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 2.985,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 28.5,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 102,
          },
          {
            name: "Protein",
            unit: "G",
            value: 29.1,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0.525,
          },
        ],
      },
      {
        name: "Potato",
        sourceName:
          "Potatoes, frozen, french fried, par fried, extruded, unprepared",
        state: "fried",
        quantity: 180,
        unit: "G",
        nutrients: [
          {
            name: "Iron",
            unit: "MG",
            value: 2.376,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 32.4,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 882,
          },
          {
            name: "Protein",
            unit: "G",
            value: 5.094,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 11.34,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 54.36,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 16.2,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 774,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.594,
          },
          {
            name: "Fat",
            unit: "G",
            value: 27,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 5.22,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Mayonnaise",
        sourceName: "Mayonnaise, Regular",
        state: "regular",
        quantity: 30,
        unit: "G",
        nutrients: [],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Fat",
        unit: "G",
        value: 47.769999999999996,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 89.47999999999999,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 581.4000000000001,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 1309.1,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 8.179,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0.829,
      },
      {
        name: "Protein",
        unit: "G",
        value: 42.754000000000005,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 12.58,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 9.273,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 81.69999999999999,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 1366.4,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 11.34,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 2.955,
      },
    ],
  },
  {
    name: "Pizza and Cola",
    servings: 2,
    comps: [
      {
        name: "Pizza",
        sourceName: "Pepperidge Farm, Goldfish, Baked Snack Crackers, Pizza",
        state: "baked",
        quantity: 300,
        unit: "G",
        nutrients: [
          {
            name: "Protein",
            unit: "G",
            value: 29.01,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 10.5,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 14.61,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 84,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 2445,
          },
          {
            name: "Fat",
            unit: "G",
            value: 56.7,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 195.3,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 279,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 978,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 3.12,
          },
        ],
      },
      {
        name: "Cola",
        sourceName: "Beverages, carbonated, cola, fast-food cola",
        state: "carbonated",
        quantity: 500,
        unit: "ML",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 0.1,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 10,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 10,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.35,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.55,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 0,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 20,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.1,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 0,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 0,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 47.8,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Protein",
        unit: "G",
        value: 14.680000000000001,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 5.25,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 7.58,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 42,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 1232.5,
      },
      {
        name: "Fat",
        unit: "G",
        value: 28.400000000000002,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 121.55000000000001,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 144.5,
      },
      {
        name: "Potassium",
        unit: "MG",
        value: 494,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 1.61,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 0,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 0,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 0,
      },
    ],
  },
  {
    name: "Fried Chicken and Fries",
    servings: 2,
    comps: [
      {
        name: "Chicken",
        sourceName: "Chicken, meatless, breaded, fried",
        state: "fried",
        quantity: 250,
        unit: "G",
        nutrients: [
          {
            name: "Potassium",
            unit: "MG",
            value: 750,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 1.625,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 30,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 1000,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 0,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 10.75,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 9.575,
          },
          {
            name: "Protein",
            unit: "G",
            value: 53.25,
          },
          {
            name: "Fat",
            unit: "G",
            value: 32,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 21.275,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 105,
          },
          {
            name: "Vitamin E",
            unit: "MG",
            value: 4.875,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 12.775,
          },
          {
            name: "Vitamin A",
            unit: "UG",
            value: 0,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Potato",
        sourceName:
          "Potatoes, frozen, french fried, par fried, extruded, unprepared",
        state: "fried",
        quantity: 220,
        unit: "G",
        nutrients: [
          {
            name: "Iron",
            unit: "MG",
            value: 2.904,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 39.6,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 1078,
          },
          {
            name: "Protein",
            unit: "G",
            value: 6.226,
          },
          {
            name: "Vitamin C",
            unit: "MG",
            value: 13.86,
          },
          {
            name: "Vitamin B12",
            unit: "UG",
            value: 0,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 66.44,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 19.8,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 946,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.726,
          },
          {
            name: "Fat",
            unit: "G",
            value: 33,
          },
          {
            name: "Fiber",
            unit: "G",
            value: 6.38,
          },
          {
            name: "Vitamin D",
            unit: "UG",
            value: 0,
          },
        ],
      },
      {
        name: "Ketchup",
        sourceName: "Ketchup, restaurant",
        state: "restaurant",
        quantity: 40,
        unit: "G",
        nutrients: [
          {
            name: "Fat",
            unit: "G",
            value: 0.22,
          },
          {
            name: "Calcium",
            unit: "MG",
            value: 5.6,
          },
          {
            name: "Iron",
            unit: "MG",
            value: 0.172,
          },
          {
            name: "Magnesium",
            unit: "MG",
            value: 5.4,
          },
          {
            name: "Potassium",
            unit: "MG",
            value: 99.6,
          },
          {
            name: "Sodium",
            unit: "MG",
            value: 379.6,
          },
          {
            name: "Zinc",
            unit: "MG",
            value: 0.064,
          },
          {
            name: "Protein",
            unit: "G",
            value: 0.444,
          },
          {
            name: "Carbohydrate",
            unit: "G",
            value: 10.72,
          },
        ],
      },
    ],
    isPublished: false,
    nutrientPerServing: [
      {
        name: "Potassium",
        unit: "MG",
        value: 897.8,
      },
      {
        name: "Zinc",
        unit: "MG",
        value: 1.2075,
      },
      {
        name: "Magnesium",
        unit: "MG",
        value: 37.5,
      },
      {
        name: "Sodium",
        unit: "MG",
        value: 1228.8,
      },
      {
        name: "Vitamin C",
        unit: "MG",
        value: 6.93,
      },
      {
        name: "Fiber",
        unit: "G",
        value: 8.565,
      },
      {
        name: "Iron",
        unit: "MG",
        value: 6.3255,
      },
      {
        name: "Protein",
        unit: "G",
        value: 29.96,
      },
      {
        name: "Fat",
        unit: "G",
        value: 32.61,
      },
      {
        name: "Carbohydrate",
        unit: "G",
        value: 49.2175,
      },
      {
        name: "Calcium",
        unit: "MG",
        value: 65.2,
      },
      {
        name: "Vitamin E",
        unit: "MG",
        value: 2.4375,
      },
      {
        name: "Vitamin B12",
        unit: "UG",
        value: 6.3875,
      },
      {
        name: "Vitamin A",
        unit: "UG",
        value: 0,
      },
      {
        name: "Vitamin D",
        unit: "UG",
        value: 0,
      },
    ],
  },
];
